# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-04-07 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20190407_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='username',
            new_name='user',
        ),
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
