# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-04-07 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20190407_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='problem_input',
        ),
    ]
