# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-04-07 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_remove_song_problem_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.CharField(max_length=250),
        ),
    ]
