# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-04-08 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20190407_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
