# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-04-09 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_auto_20190409_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
